set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(RK3588_TOOLCHAIN_PREFIX "aarch64-linux-gnu" CACHE STRING "GNU triplet prefix for the RK3588 cross toolchain")
set(CMAKE_SYSROOT "" CACHE PATH "Sysroot for the RK3588 target rootfs")

set(CMAKE_C_COMPILER "${RK3588_TOOLCHAIN_PREFIX}-gcc" CACHE FILEPATH "C compiler")
set(CMAKE_CXX_COMPILER "${RK3588_TOOLCHAIN_PREFIX}-g++" CACHE FILEPATH "C++ compiler")
set(CMAKE_ASM_COMPILER "${RK3588_TOOLCHAIN_PREFIX}-gcc" CACHE FILEPATH "ASM compiler")

if(CMAKE_SYSROOT)
    set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)